# Generated by Django 4.0.6 on 2022-07-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xayrehsonapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xayrehson',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
